### ISSUE TITLE
Cannot compile on Windows

### ISSUE THREAD

**Issue by caecos** [dirkleas/DLwigglz#4]
$ RACK_DIR=C:/msys64/Rack-SDK make dist
g++  -Wsuggest-override -std=c++11  -DSLUG=DLwigglz -fPIC -IC:/msys64/Rack-SDK/include -IC:/msys64/Rack-SDK/dep/include -DVERSION=0.6.0 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/DLwigglz.cpp.o src/DLwigglz.cpp
g++  -Wsuggest-override -std=c++11  -DSLUG=DLwigglz -fPIC -IC:/msys64/Rack-SDK/include -IC:/msys64/Rack-SDK/dep/include -DVERSION=0.6.0 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/R4xH4x.cpp.o src/R4xH4x.cpp
src/R4xH4x.cpp:14:10: fatal error: sys/mman.h: No such file or directory
 #include <sys/mman.h>
          ^~~~~~~~~~~~
compilation terminated.
make: *** [C:/msys64/Rack-SDK/compile.mk:65: build/src/R4xH4x.cpp.o] Error 1

**Comment by dirkleas** [comment]
I've posted a new commit resolving the sys/mman.h issue (sorry, was experimenting and included references to libs implemented differently on windows). Oddly enough, I'm only able to build this plugin with a full VCV Rack source tree -- the 0.6.1 SDK is generating the following (same error occurs with fresh pull of official VCV Rack [Template](https://github.com/VCVRack/Template)):

```
$ cd DLwigglz/

Dirk@DESKTOP-LP2A1RC MINGW64 ~/h4x/DLwigglz
$ RACK_DIR=../Rack-SDK make dist
g++ -o plugin.dll build/src/DLwigglz.cpp.o build/src/R4xH4x.cpp.o  -shared -L../Rack-SDK -lRack
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lRack
collect2.exe: error: ld returned 1 exit status
make: *** [../Rack-SDK/compile.mk:55: plugin.dll] Error 1

Dirk@DESKTOP-LP2A1RC MINGW64 ~/h4x/DLwigglz
$ ls ..
DLwigglz  Rack  rackcli  Rack-SDK  Rack-SDK-0.6.0.zip  Rack-SDK-0.6.1.zip
```

I'm researching this. In the meantime, sorry for the inconvenience, and I'll upload [binaries](https://github.com/dirkleas/DLwigglz/releases) for Windows, Linux, and MacOS.

**Comment by dirkleas** [comment]
previous comment issue casuse: 0.6.1 version of rack-sdk has dropped requisite libRack.a -- grabbed libRack.a from a full rack source build and the sdk build behaved as expected

**Comment by dirkleas** [comment]
please re-download official [rack-sdk](https://github.com/VCVRack/Rack/issues/258) -- it has been updated to include the missing `libRack.a` library needed to resolve the build error above
